workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: "ProductivityApp.xcodeproj"
        XCODE_SCHEME: "ProductivityApp"
        XCODE_ARCHIVE_PATH: "$HOME/build/ProductivityApp.xcarchive"
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods || echo "CocoaPods ya instalado"
          pod install --repo-update || echo "Pods ya instalados"
      - name: Build iOS app
        script: |
          xcodebuild -project $XCODE_PROJECT \
            -scheme $XCODE_SCHEME \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $XCODE_ARCHIVE_PATH
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $XCODE_ARCHIVE_PATH \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $HOME/build/ios_output
    artifacts:
      - $HOME/build/ios_output/*.ipa
      - $HOME/build/ios_output/*.dSYM.zip
      - $HOME/build/ProductivityApp.xcarchive
